"""empty message

Revision ID: 83a06d4f0716
Revises: d837055700ab
Create Date: 2025-02-15 20:52:18.076067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83a06d4f0716'
down_revision = 'd837055700ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_lent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('lent_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('lent_at')
        batch_op.drop_column('is_lent')

    # ### end Alembic commands ###
